services:
  nginx:
    image: nginx:alpine
    ports:
      - "5173:5173"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

  frontend:
    build: ./frontend
    image: vijayv2468/interview-frontend:latest
    environment:
      - VITE_API_URL=http://localhost:5173/api
    expose:
      - "5173"

  backend:
    build: ./backend
    image: vijayv2468/interview-backend:latest
    environment:
      - PYTHONUNBUFFERED=1
    expose:
      - "8000"